#[[plugins]] # Plugin to easily access Most Recently Used (MRU) files
#repo = 'Shougo/neomru.vim'
#on_source = 'denite.nvim'
#on_path = '.*'
#
#[[plugins]] # Yank
#repo = 'Shougo/neoyank.vim'
#on_source = 'denite.nvim'
#on_event = 'TextYankPost'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_event = 'InsertCharPre'
on_ft = 'snippet'
depends = 'context_filetype.vim'
hook_source = '''
source ~/.config/nvim/plugins/neosnippet.rc.vim
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
on_event = 'InsertEnter'
hook_source = '''
source ~/.config/nvim/plugins/deoplete.rc.vim
'''
